### ISSUE TITLE
Make Fn Key work ?

### ISSUE THREAD

**Issue by nhdanh** [MohammadtaghiFarkhondekar/macOS-For-Asus-ROG-GL553VD#1]
Have you any solution for Fn Key work ? I only use Fn+ f10 f11 f12. Thank you

**Comment by MohammadtaghiFarkhondekar** [comment]
Hi. media FN keys working. F10+f11+f12+ up+down+right+left . 
but FN negative by apple for the backlight of the screen working.
you can develop Asus FN keys and add it to the project .
thank you.
