### ISSUE TITLE
Audio doesn't work

### ISSUE THREAD

**Issue by Linkadi98** [MohammadtaghiFarkhondekar/macOS-For-Asus-ROG-GL553VD#10]
Hi, 
Thanks for your clover file. Every thing works fine including full acceleration. But, the audio doesn't work for some reasons. I tried replace the AppleALC with the latest version but it doesn't work, too. I saw in your test video the audio worked fine, but I don't get it :v

**Comment by MohammadtaghiFarkhondekar** [comment]
Hi . 
What's your laptop model ? Gl553vd ? Or fx ?
For working audio you most turn off your laptop on Windows not restart ! 
After turn off full , turn on again and go to the Mac OS . 
Just use Mac os 10.14.3 up ...
Never it work on hand made *hack v * of Mac os . ****Never work on Niresh****

**Comment by Linkadi98** [comment]
Hi,
Am using Niresh to install mojave, like you said it never works. 
I am making my own new usb installer with the official release of mojave 10.14.5 from apple store.
I just have one question now: your clover file will work with this version of mojave? 
Thank you for your work.

**Comment by MohammadtaghiFarkhondekar** [comment]
Yes . It most work on 10.14.3 up to 10.14.6 !

**Comment by Linkadi98** [comment]
Thank you

**Comment by Linkadi98** [comment]
Hi,
I know it is really weird but when I restart my mac a couple of times and I put the voodooHDA to the Other folder, it's magically, the audio works perfectly.

**Comment by MohammadtaghiFarkhondekar** [comment]
use V7
