### ISSUE TITLE
Bluetooth not work

### ISSUE THREAD

**Issue by ezemedina** [MohammadtaghiFarkhondekar/macOS-For-Asus-ROG-GL553VD#11]
Hi thaks for the plist!, the bluetooth not work i ask on tonymacx86 and say is not compatible
![Captura de Pantalla 2019-07-14 a la(s) 18 09 59](https://user-images.githubusercontent.com/52898358/61191737-b2e70080-a662-11e9-8803-6da27f3754cc.png)

**Comment by MohammadtaghiFarkhondekar** [comment]
Hi .
What's your Mac os v ?
What's your laptop model ? 
What's your wireless card model ?
Asus GL553VD with Intel card is ok for having Bluetooth.

**Comment by MohammadtaghiFarkhondekar** [comment]
Use V7 with mac os 10.14.5
