### ISSUE TITLE
[CLOVER V7] Audio distortion

### ISSUE THREAD

**Issue by tuanngokien** [MohammadtaghiFarkhondekar/macOS-For-Asus-ROG-GL553VD#13]
After upgrade my clover to v7 last few days, i just found out that audio is distorted so i can't hear musician's voice anymore. I solved this problem by downgrade AppleALC from 1.3.9 to 1.3.6, which you had in previous version.

**Comment by MohammadtaghiFarkhondekar** [comment]
Oh oh . I will talk with audio kext developer .

**Comment by MohammadtaghiFarkhondekar** [comment]
Fixed in V8
