### ISSUE TITLE
[CLOVER V7] System is much delay after long work

### ISSUE THREAD

**Issue by tuanngokien** [MohammadtaghiFarkhondekar/macOS-For-Asus-ROG-GL553VD#14]
System is much delay after long work. I think the cause is GPU

**Comment by MohammadtaghiFarkhondekar** [comment]
Use preference mode . !
In power saving mode CPU limited.

**Comment by tuanngokien** [comment]
I'm using performance clover, and this bug has happened

**Comment by MohammadtaghiFarkhondekar** [comment]
Use Intel power app for monitor CPU .

**Comment by tuanngokien** [comment]
<img width="422" alt="Screen Shot 2019-07-30 at 2 37 51 PM" src="https://user-images.githubusercontent.com/26508575/62110229-2d0cbb80-b2d8-11e9-8e91-d54f54d1e632.png">
CPU was keeping on high frequency, but mac os was still running on hight frequency.
So i think i should revert to v6 version for daily use

**Comment by MohammadtaghiFarkhondekar** [comment]
Fixed in V8
