### ISSUE TITLE
Screen Waves

### ISSUE THREAD

**Issue by FerVillanuevas** [MohammadtaghiFarkhondekar/macOS-For-Asus-ROG-GL553VD#15]
I don't know if it's just on my screen, but in waves or in the osx blur you can see waves of colors, you don't see a uniform color

Thank you for all of your work

**Comment by MohammadtaghiFarkhondekar** [comment]
It's just in your laptop screen , I test this project in other gl553vd and screen is okay . 
Check your laptop screen in Windows or Linux ...
