### ISSUE TITLE
Audio and Trackpad not working after update to 10.14.6 last

### ISSUE THREAD

**Issue by fgarioli** [MohammadtaghiFarkhondekar/macOS-For-Asus-ROG-GL553VD#16]
After update to 10.14.6 (last update) my audio and trackpad stopped to work. For solve, beyond to remove AppleIntelLpssI2CController.kext and AppleIntelLpssI2C.kext, like in description, I removed AppleHPM.kext too. So it was solved. If this can it helps someone, I will be happy.

**Comment by MohammadtaghiFarkhondekar** [comment]
Which clover v do you use ? V7 ?

**Comment by fgarioli** [comment]
Yes, I'm using V7. It was necessary besides that to downgrade the audio kext to V5 (I replaced the file in the clover folder).

**Comment by fgarioli** [comment]
> Which clover v do you use ? V7 ?
Yes, I'm using V7. It was necessary besides that to downgrade the audio kext to V5 (I replaced the file in the clover folder).

**Comment by MohammadtaghiFarkhondekar** [comment]
Fixed in V8
