### ISSUE TITLE
System suddenly signed out on connecting HDMI on Mojave 10.14.6 

### ISSUE THREAD

**Issue by tuanngokien** [MohammadtaghiFarkhondekar/macOS-For-Asus-ROG-GL553VD#18]
System suddenly signed out on connecting HDMI on Mojave 10.14.6

**Comment by MohammadtaghiFarkhondekar** [comment]
which v of clover do you use ? v8 ?

**Comment by tuanngokien** [comment]
Yes,  i'm using v8

**Comment by MohammadtaghiFarkhondekar** [comment]
problem by your HDMI cable  or your apps in macos 10.14.6 bc i test v9 and v8 in 10.14.6 and 10.15 beta 8 all of clover work very good .

**Comment by tuanngokien** [comment]
should i prefer v9 for 10.14.6?

**Comment by shivaluma** [comment]
Is it worth to replace my current 10.14.6 mojave with the new catalina? 
And can mojave use the v9 efi ? ( oh i realised that v9 is only for 10.15)
Thank you.

**Comment by MohammadtaghiFarkhondekar** [comment]
@tuanngokien you can , but in v9 fn keys of Asus Aura keyboard don't working ...
@shivaluma you can upload , just Asus Aura keyboard fn keys don't working ...
