### ISSUE TITLE
Hello! Why not try my GL553VD EFI?

### ISSUE THREAD

**Issue by QiuChenly** [MohammadtaghiFarkhondekar/macOS-For-Asus-ROG-GL553VD#2]
it is in this : https://git.lug.ustc.edu.cn/QiuChenly/ASUS_FX53VD_10.13.1EFI
What's not working:
1.Keyboard backlight control and FN.
2.you tell me.

What's working:
The sleep, the trackpad, the Apple ALC, and all the other special features.

**Comment by tuanngokien** [comment]
his efi is currently having the same issues as you

**Comment by MohammadtaghiFarkhondekar** [comment]
Hi. 
because this laptop has a USB keyboard and it's aura keyboard it needs Asus aura core API for Linux !! 
but sleeping, trackpad, APPLEALC (id 16 add for gl553vd ) and others are working good.
*** fx553 has Different type motherboard and keyboard than asus rog gl553vd *** they aren't same !!
