### ISSUE TITLE
My usb drive can only be recognized by the USB 2.0 port

### ISSUE THREAD

**Issue by shivaluma** [MohammadtaghiFarkhondekar/macOS-For-Asus-ROG-GL553VD#21]
Like the title that i can only see my usb drive partition when i plugged it into the usb 2.0 port on the right side of GL553VD. Both port on the left size couldn't help. It has been happened since two recent version i think.

**Comment by MohammadtaghiFarkhondekar** [comment]
Wich v of clover do you use ? All of usb work very good .

**Comment by shivaluma** [comment]
i only have a sandisk cruzer glide 3.0 and im using v9 clover, but v8 has the same result

**Comment by MohammadtaghiFarkhondekar** [comment]
I will check it 👍

**Comment by tuanngokien** [comment]
I has just noticed that I'm having the same issue on External HDD while plugging through USB 3.0 port (both on the left side), and USB 2.0 port seem still working

**Comment by nhdanh** [comment]
I has same problem with v9 CLOVER

**Comment by MohammadtaghiFarkhondekar** [comment]
FIXED in V10
