### ISSUE TITLE
I noticed my laptop is not as fast when using Clover-V8

### ISSUE THREAD

**Issue by AdriaanRoets** [MohammadtaghiFarkhondekar/macOS-For-Asus-ROG-GL553VD#22]
I could not get your CLOVER files working on my install the last couple of days and then resorted to another EFI Folder I found online. I got Mojave working with it but there were lots of things not working. I finally got your CLOVER-V8 working tonight (fast boot was never disabled, caused screen "garble" on boot).
I am happy and everything works! Only one problem. I am noticing that Mojave is not as fast anymore.. Sometimes when I type words are slow to come and applications are not as responsive as before. I have Asus ROG GL553VD, but i5 7300HQ version. I am wondering if this could be the cause? I am not very proficient with Clover Configurator and do not know how to check what can be the cause. Do you have any ideas where I can start to look for the cause? Thanks!

**Comment by AdriaanRoets** [comment]
I have noticed that after leaving my computer on over night to complete all background processes, and it's now running smooth! If there's anything that I do however need to change because of my i5 processor version, please let me know. Thanks.

**Comment by shivaluma** [comment]
where is he ?

**Comment by MohammadtaghiFarkhondekar** [comment]
FIXED in V10
