### ISSUE TITLE
Patch for asus aura in 10.14.6 v10

### ISSUE THREAD

**Issue by tuanngokien** [MohammadtaghiFarkhondekar/macOS-For-Asus-ROG-GL553VD#25]
I have just updated your latest version v10 for my 10.14.6, but aura keyboard didn't work anymore, hope you released v10 mojave version soon

**Comment by tuanngokien** [comment]
I just make it work by moving AsusSMC kext to Clover, so I think you should note in in README.md for further optional setup

**Comment by MohammadtaghiFarkhondekar** [comment]
Hi, Asus smc has problems with Mac OS for it I removed that ! 
It will come back in v11 .

**Comment by tuanngokien** [comment]
Could you mention more detail about the problem with SMC?

**Comment by MohammadtaghiFarkhondekar** [comment]
Test in 10.15 and know  !
