### ISSUE TITLE
No trackpads found in V10, And the CPU is hotter than normal

### ISSUE THREAD

**Issue by shivaluma** [MohammadtaghiFarkhondekar/macOS-For-Asus-ROG-GL553VD#26]
I cant use my trackpad in V10 but on V9 its work like a charm
And my cpu increase about 5 degree celsius when updated to Catalina i think,
do you have any solution for this ? 
Thank you.

**Comment by shivaluma** [comment]
i think my tempe is ok when using your V10, so could you show me how to fix the trackpad pls

**Comment by MohammadtaghiFarkhondekar** [comment]
Hi . Touchpad just working in 10.15 ,( not beta ! In beta just working in 10.15 beta9 )  !
After installing you had to use guide and clear system cache !

**Comment by shivaluma** [comment]
Im using Catalina 10.15.1 Beta
I cant delete AppleIntelLpssI2C*.kext in S/L/E cuz the system is now readonly.
how can i fix this >.<

**Comment by MohammadtaghiFarkhondekar** [comment]
Install Mac is 10.15 public v ! It doesn't need to delete anything, just run the cleaning cache code in public v !

**Comment by shivaluma** [comment]
u meant "sudo kextcache -i /" right?
i have tried it many times but no luck

**Comment by MohammadtaghiFarkhondekar** [comment]
Yes .
Your MacOS is not good for gl553vd ! Use 10.15 public v not beta v !or use beta 9 ! Not other v of MacOS !

**Comment by shivaluma** [comment]
I am using latest version of macOS 10.15.1 Beta 1
Now its have .2 but i think my macOS is newer than the 10.15 public

**Comment by MohammadtaghiFarkhondekar** [comment]
Touch pad never work in beta ! Just in beta 9 or public v ! Not other v !
