### ISSUE TITLE
Keyboard doesn't work on GL553VE

### ISSUE THREAD

**Issue by serhiicherepanov** [MohammadtaghiFarkhondekar/macOS-For-Asus-ROG-GL553VD#27]
Hi, I was successful with your v10 config.

Looks works fine instead the builtin keyboard.

Do you have idea what is wrong?

Thanks!

**Comment by e-senturk** [comment]
Asus smc breaks keyboard in catalina for now

**Comment by serhiicherepanov** [comment]
Hi @valinor61, 

But I tried it on the Mojave. I think the issue in the DSDT patches because my model a little bit different. I will try to apply patches to my original tables.
