### ISSUE TITLE
Functional Keys don't work

### ISSUE THREAD

**Issue by keinsell** [MohammadtaghiFarkhondekar/macOS-For-Asus-ROG-GL553VD#29]
I'm using Catalina 10.15 and there is a bit weird issue with functional keys, maybe re-mapping with `VoodooPS2` will help but I haven't tested that.

Functional Keys associated with Volume works well, but when you're trying to use other keys for other functions they are recognized but don't perform any action, maybe it's a problem with Catalina but I don't think so, do somebody have experienced similar issue on Mojave 10.14.X?

**Comment by e-senturk** [comment]
problem comes with asussmc kext its not working on catalina right now so its removed for now

**Comment by MohammadtaghiFarkhondekar** [comment]
It will fix in New V ....
