### ISSUE TITLE
Color Profile

### ISSUE THREAD

**Issue by Mateo1234454545** [MohammadtaghiFarkhondekar/macOS-For-Asus-ROG-GL553VD#3]
Hi.
Do you have any color profile for the NV156FHM-N43 on MacOs?
Thanks in advance.

**Comment by MohammadtaghiFarkhondekar** [comment]
Hi . 
You can get it from Asus display app for your model . 
I will make video Training for it .

**Comment by Mateo1234454545** [comment]
I don't have an Asus laptop , but I have the same display and I'm trying to find a proper color profil for it.

**Comment by MohammadtaghiFarkhondekar** [comment]
I haven't any idea for it . But in Asus laptop you can get it from Asus display app .
Good luck

**Comment by Mateo1234454545** [comment]
It is at /Library/Colorsync/profiles folder. Would you mind upload the conents of the folder for me?

**Comment by MohammadtaghiFarkhondekar** [comment]
[icm.zip](https://github.com/MohammadtaghiFarkhondekar/macOS-Mojave-For-Asus-ROG-GL553VD/files/3116697/icm.zip)
