### ISSUE TITLE
Speaker Volume too Low!

### ISSUE THREAD

**Issue by ImranKhan198422** [MohammadtaghiFarkhondekar/macOS-For-Asus-ROG-GL553VD#30]
Everything working fine except speaker volume of laptop GL553VF

**Comment by MohammadtaghiFarkhondekar** [comment]
I know! Use boom 3D .

**Comment by e-senturk** [comment]
There is a new layout for our device you can also try it its 22

**Comment by ImranKhan198422** [comment]
> There is a new layout for our device you can also try it its 22

Not working, still very low.

**Comment by ImranKhan198422** [comment]
> I know! Use boom 3D .

Its working but there are disadvantages of boom3d
1> it's not free. you have to buy it after 30 days 
2> system sounds are still low. 
3> App is draining battery quickly

**Comment by MohammadtaghiFarkhondekar** [comment]
It's Linux code and I can't do anything for it ! In windows Asus audio app fix this problem.
