### ISSUE TITLE
Fan works on full speed.

### ISSUE THREAD

**Issue by serhiicherepanov** [MohammadtaghiFarkhondekar/macOS-For-Asus-ROG-GL553VD#32]
Hi! In first thanks for your work!

I still playing with my GL553VE, and now it almost works fine, except the fan. It always run on the full speed. May be you know how to resolve it?

Also small request, could you add more description about your dsdt/ssdt patches? Currently it's hard to understand for newbies (what is needed for what).

**Comment by MohammadtaghiFarkhondekar** [comment]
Just use my SSD patch . Because you can't turn off GTX and fun speed go to 💯 .

**Comment by serhiicherepanov** [comment]
Hi @MohammadtaghiFarkhondekar, yes previously I used another patch for GTX off. Witch your patch issue is gone.

Thanks!

**Comment by MohammadtaghiFarkhondekar** [comment]
I will write about it.
