### ISSUE TITLE
Some mini bugs and improve

### ISSUE THREAD

**Issue by shivaluma** [MohammadtaghiFarkhondekar/macOS-For-Asus-ROG-GL553VD#34]
Im using your latest version v11 and im facing some mini issues like
1. the sleep mode cant fully sleep like windows, its only turn off the screen, and the fans keep running too.
2. sometime the speakers cant output sound and need reboot

i saw that asussmc have updates on catalina so could you bring it back again ?
Thank you.

**Comment by MohammadtaghiFarkhondekar** [comment]
Next week I will send V12 .
