### ISSUE TITLE
Trackpad sometimes stopped to work for a while

### ISSUE THREAD

**Issue by tuanngokien** [MohammadtaghiFarkhondekar/macOS-For-Asus-ROG-GL553VD#35]
I'm using your V11 Clover with Mojave 10.14.6. During using daily task, the trackpad (touchpad) stopped to work for a while (3 minutes) and  suddenly come back normally. Could you make aware and find the solution?

**Comment by iSWORD** [comment]
I'm having the same issue on V11

**Comment by MohammadtaghiFarkhondekar** [comment]
Next week I will send V12 .
