### ISSUE TITLE
Battery 

### ISSUE THREAD

**Issue by FerVillanuevas** [MohammadtaghiFarkhondekar/macOS-For-Asus-ROG-GL553VD#4]
Bro, the battery is consumed super fast, I'm using "High Sierra"

**Comment by MohammadtaghiFarkhondekar** [comment]
Hi.
Just use [v5-Main ](https://github.com/MohammadtaghiFarkhondekar/macOS-Mojave-For-Asus-ROG-GL553VD/releases/tag/v5-Main)+ Mojave for getting 4 hours to 6:30 hours battery life.

**Comment by FerVillanuevas** [comment]
Ty bro!, thank for your work.
