### ISSUE TITLE
Can this guide still good for asus ROG GL503VD (strix hero) too ?

### ISSUE THREAD

**Issue by tuanhm11299** [MohammadtaghiFarkhondekar/macOS-For-Asus-ROG-GL553VD#40]
Like my title, my laptop has hardware as same as GL553VD, but I wonder is this guide still good for my laptop ?
Hope I can know your sharing.

**Comment by MohammadtaghiFarkhondekar** [comment]
Yes you can use !! You need set your cpu ....
