### ISSUE TITLE
Has anyone had trouble updating to macOS 10.5.5?

### ISSUE THREAD

**Issue by dancarvajalc** [MohammadtaghiFarkhondekar/macOS-For-Asus-ROG-GL553VD#43]
Hi, i'm on 10.5.3 and i don't have updated to the last version of Catalina. I once read in reddit when macOS 10.5.4 released there was a little problems, but i don't remember well.

Someone updated to the last version without problems?

Sorry for my english and thank you in advance.

**Comment by keinsell** [comment]
I had problems when I was updating to 10.5.3 from 10.5.1 - I don't figured why my OS got totally crashed in update process, but reinstall to newer version of MacOS solved issue.
