### ISSUE TITLE
Getting KP with the HDMI version

### ISSUE THREAD

**Issue by abanerjee123** [MohammadtaghiFarkhondekar/macOS-For-Asus-ROG-GL553VD#5]
I have FX553VD with i7 7700HQ and NVIDIA 1050. Your non HDMI version working fine but with HDMI my laptop is restarting . Didi you test the HDMI version?

**Comment by MohammadtaghiFarkhondekar** [comment]
Hi.
FX553 has different motherboard for it HDMI v restarting . do you use it on mac os 10.14.4?
((( In HDMI v gtx1050 is on. but I set it on Power status 3 .)))

**Comment by abanerjee123** [comment]
Yes I am using 10.14.4. I checked in window that my HDMI is connected to Intel HD630 but some how it is not working. I saw if I removed the ssdt which disable NVIDIA it is restating. Non HDMI version is working absolutely fine.

**Comment by MohammadtaghiFarkhondekar** [comment]
HDMI always contact to Nvidia ! In this laptop !
When using HDMI V, you most not contact the HDMI coble before system 100% booting !

**Comment by abanerjee123** [comment]
I will try surely Thanks

**Comment by abanerjee123** [comment]
HDMI version is working fine. But some how boot is slow. Are you also facing same? Thanks a lot. I was struggling for HDMI for long time.

**Comment by MohammadtaghiFarkhondekar** [comment]
Yes! just for Nvidia!
