### ISSUE TITLE
Audio Problem

### ISSUE THREAD

**Issue by mefizh** [MohammadtaghiFarkhondekar/macOS-For-Asus-ROG-GL553VD#6]
Hi man, my laptop is GL553VE, just the GPU different. I've already follow your steps and install with your clover, all seems okay until i released my audio is not working. any help will be appreciated

**Comment by MohammadtaghiFarkhondekar** [comment]
Hi .
You don't need to replace any things in the Mac os . use the Mac OS 10.14.4 .
Use last v of my clover for booting .

**Comment by mefizh** [comment]
Okay i'll try again. i will be share if i succeed

**Comment by mefizh** [comment]
Hi, this is my update. The audio is still no sound out or in. At the end, now im using voodoo its okay with me my hackintosh is not vanilla. But many thanks for creating this clover. finally i can work with my external monitor. 

im still wondering, it is possible to switch between main version and the hdmi version, bcs i still using this laptop for outdoor too.

So many thanks once again brother!
