### ISSUE TITLE
Mojave 10.14.4

### ISSUE THREAD

**Issue by tuanngokien** [MohammadtaghiFarkhondekar/macOS-For-Asus-ROG-GL553VD#7]
I'm using your latest clover version in mac os 10.14.3 and i have seen that apple released 10.14.4, have you tried to upgrade to this, i'm confusing if my gl553vd will work well when i take this

**Comment by MohammadtaghiFarkhondekar** [comment]
Hi .
Yes . You can update . I'm using Mac os 10.14.4 with out problem.

**Comment by Linkadi98** [comment]
Hi @tuanngokien, ông cài đặt macos như thế nào vậy, t có dùng Niresh Mojave cài nhưng có vẻ như nó bị lỗi nhiều ở phần hình ảnh, k biết thay Clover của anh bạn này có dùng được không nhỉ?

**Comment by tuanngokien** [comment]
I should try this
https://git.lug.ustc.edu.cn/QiuChenly/ASUS_FX53VD_10.13.1EFI
I know FX553VD is almost the same hardware but there are still some difference that would make some bugs while experience. Otherwise, you should build Installation yourself or download it from olarila (instead of zone), and also join VN hackintosh on FB for perfecting your Hackintosh
