### ISSUE TITLE
Mojave on FX553VD

### ISSUE THREAD

**Issue by Linkadi98** [MohammadtaghiFarkhondekar/macOS-For-Asus-ROG-GL553VD#8]
Hi, I am digging in Mojave on my laptop which has a GL553VD main board, but now I have to try to re-install my mac for reasons about my main board, I wonder if it is comfortable for my laptop to use this Clover file?

**Comment by MohammadtaghiFarkhondekar** [comment]
Hi . Yes you can use .

**Comment by tuanngokien** [comment]
How about Mojave 10.14.5?

**Comment by Linkadi98** [comment]
Thank you!

**Comment by MohammadtaghiFarkhondekar** [comment]
Yes . You can use with 10.14.5 !
