### ISSUE TITLE
Sleep problem on Mojave 10.14.4

### ISSUE THREAD

**Issue by nhdanh** [MohammadtaghiFarkhondekar/macOS-For-Asus-ROG-GL553VD#9]
Im using v5 main release. I cannot sleep my laptop. When choose sleep on menu. The screen off and keyboard still light, fan or usb still working.  Type any key. The screen on again. It not sleep. How can I fix that sleep problem ?

**Comment by MohammadtaghiFarkhondekar** [comment]
I'm working on it but I think it never fix !

**Comment by nhdanh** [comment]
Ok. Im loking forward to your results
